image: openbsd/latest
oauth: pages.sr.ht/PAGES:RW
packages:
- coreutils--
- gsed--
- cmake--
- gcc--
- lowdown--
- go--
environment:
site: bt.srht.site
sources:
- https://git.sr.ht/~bt/btxx.org
tasks:
- install-hut: |
    git clone https://git.sr.ht/~xenrox/hut
    cd hut
    make
    doas make install
- build: |
    cd btxx.org
    make build
- package: |
    cd btxx.org/build
    tar -cvz . > ../../site.tar.gz
- upload: |
    hut pages publish -d bt.srht.site site.tar.gz
