image: alpine/latest
oauth: pages.sr.ht/PAGES:RW
packages:
- ruby
- go
- hut
environment:
site: bt.srht.site
sources:
- https://git.sr.ht/~bt/btxx.org
tasks:
- install-gems: |
    sudo gem install kramdown fileutils rss
- build: |
    cd btxx.org
    make build
- package: |
    cd btxx.org/build
    tar -cvz . > ../../site.tar.gz
- upload: |
    hut pages publish -d bt.srht.site site.tar.gz
