image: alpine/latest
oauth: pages.sr.ht/PAGES:RW
packages:
- ruby
- go
- hut
environment:
site: btxx.org
sources:
- https://git.sr.ht/~bt/btxx.org
tasks:
- install-gems: |
    sudo gem install kramdown rss
- build: |
    cd btxx.org
    make build
- package: |
    cd btxx.org/build
    tar -cvz . > ../../site.tar.gz
- upload: |
    hut pages publish -d btxx.org site.tar.gz
