image: alpine/latest
oauth: pages.sr.ht/PAGES:RW
packages:
- ruby-full
- ruby-dev
- rsync
- coreutils
- go
- hut
environment:
site: bt.srht.site
sources:
- https://git.sr.ht/~bt/btxx.org
tasks:
- install-kramdown: |
    sudo gem install kramdown
- build: |
    cd btxx.org
    make build
- package: |
    cd btxx.org/build
    tar -cvz . > ../../site.tar.gz
- upload: |
    hut pages publish -d bt.srht.site site.tar.gz