image: alpine/latest
oauth: pages.sr.ht/PAGES:RW
packages:
- ruby
- ruby-dev
- go
- hut
environment:
site: btxx.org
sources:
- https://git.sr.ht/~bt/btxx.org
tasks:
- install-gems: |
    sudo gem install bundler 'kramdown:2.4.0' 'rss:0.3.0'
- build: |
    cd btxx.org
    sudo make build
- package: |
    cd btxx.org/build
    tar -cvz . > ../../site.tar.gz
- upload: |
    hut pages publish -d btxx.org site.tar.gz
